apiVersion: v1
kind: Service
metadata:
  name: rewards-api
  labels:
    app: rewards-api
spec:
  ports:
    - port: 8000
  selector:
    app: rewards-api
    tier: backend-api
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: rewards-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rewards-api
  labels:
    app: rewards-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rewards-api
      tier: backend-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rewards-api
        tier: backend-api
    spec:
      initContainers:
        - name: setup-storage
          image: busybox
          command: ["sh", "-c", "mkdir -p /var/www/html/storage/framework/views/ && mkdir -p /var/www/html/storage/framework/cache/ && mkdir -p /var/www/html/storage/framework/sessions/ && chown -R www-data:www-data /var/www/html/storage/framework/sessions/"]
          volumeMounts:
            - name: rewards-api-persistent-storage
              mountPath: /var/www/html/storage
      containers:
        - image: almatyartem/rewards:1
          name: rewards-api
          envFrom:
            - secretRef:
                name: rewards-secrets
          ports:
            - containerPort: 8000
              name: rewards-api
          volumeMounts:
            - name: rewards-api-persistent-storage
              mountPath: /var/www/html/storage
      volumes:
        - name: rewards-api-persistent-storage
          persistentVolumeClaim:
            claimName: wp-pv-claim
