apiVersion: v1
kind: Service
metadata:
  name: rewards-mysql
  labels:
    app: rewards
spec:
  ports:
    - port: 3306
  selector:
    app: rewards
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rewards-mysql-pv-claim
  labels:
    app: rewards
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rewards-mysql
  labels:
    app: rewards
spec:
  selector:
    matchLabels:
      app: rewards
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rewards
        tier: mysql
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rewards-secrets
                  key: DB_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: rewards-secrets
                  key: DB_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: rewards-secrets
                  key: DB_USERNAME
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rewards-secrets
                  key: DB_PASSWORD
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: rewards-mysql-pv-claim
